apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wall-e-ingress
  namespace: ns-wall-e-springboot
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: wall-e.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wall-e-springboot
            port:
              number: 8080