apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wall-e-ingress
  namespace: ns-wall-e-springboot
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: wall-e.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wall-e-backend
            port:
              number: 443