apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: kafka
spec:
  type: NodePort
  selector:
    app: schema-registry
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30002   # tu peux changer si 30002 est déjà utilisé
schema-registry-svc.yaml
