apiVersion: apps/v1
kind: Deployment
metadata:
  name: akhq
  namespace: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akhq
  template:
    metadata:
      labels:
        app: akhq
    spec:
      containers:
      - name: akhq
        image: tchiotludo/akhq:0.26.0
        ports:
          - containerPort: 8080
        env:
          - name: AKHQ_CONFIGURATION
            value: |
              akhq:
                connections:
                  local:
                    properties:
                      bootstrap.servers: "my-kafka:9092"
                    schema-registry:
                      url: "http://schema-registry:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: akhq
  namespace: kafka-ui
spec:
  type: ClusterIP
  selector:
    app: akhq
  ports:
    - port: 80
      targetPort: 8080